import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.InputMismatchException;
import java.util.Scanner;


public class TestException {

	static int input(){
		int re = 0;
		Scanner scanner = new Scanner(System.in);
		
		re = scanner.nextInt();
		
		return re;
	}
	public static void process(){
		// TODO Auto-generated method stub
		try {
			System.out.print("Enter First number: ");
			int x = input();
			System.out.print("Enter Second number: ");
			int y = input();
		
			System.out.println(x/y);
		} catch (ArithmeticException e) {
			// TODO: handle exception
			System.out.println("Exception : div by zero");
		}catch (InputMismatchException e) {
			// TODO: handle exception
				System.out.println("Exception...");
		}catch (Exception e) {
			// TODO: handle exception
			System.out.println("all Exception...");
		}
		
		
	}
	
	static int readInput(){
		File file = new File("E:/xa.txt");
		try {
			Scanner sc = new Scanner(file);
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
			return -1;
		}catch (IOException e) {
			// TODO: handle exception
			return -1;
		}
		finally{
			System.out.print("finally");
		}
		return 0;
	}
	public static void main(String args[]) {
		// TODO Auto-generated method stub
		//process();
		
		readInput();
		
		
		System.out.print("Bye");
	}

}
